////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------

//namespace N_391823086
//{
//    using Newtonsoft.Json.Linq;
//    using Bb.ComponentModel.Factories;
//    using Bb.Json.Jslt.Services;
//    using System;
//    using System.Diagnostics;


//    public class Myclass
//    {

//        private Factory<Newtonsoft.Json.Linq.JToken> srv_0;

//        private string[] srv_1;

//        private Factory<Bb.Json.Jslt.Services.ITransformJsonService> srv_2;

//        private string[] srv_3;

//        private Factory<Bb.Json.Jslt.Services.ITransformJsonService> srv_4;

//        private string[] srv_5;

//        private string[] srv_6;

//        public Myclass(object[] args)
//        {
//            this.srv_0 = ((Factory<Newtonsoft.Json.Linq.JToken>)(args[0]));
//            this.srv_1 = ((string[])(args[1]));
//            this.srv_2 = ((Factory<Bb.Json.Jslt.Services.ITransformJsonService>)(args[2]));
//            this.srv_3 = ((string[])(args[3]));
//            this.srv_4 = ((Factory<Bb.Json.Jslt.Services.ITransformJsonService>)(args[4]));
//            this.srv_5 = ((string[])(args[5]));
//            this.srv_6 = ((string[])(args[6]));
//        }

//        public virtual JToken MyMethod(RuntimeContext argContext, JToken argToken)
//        {
//            JObject var_JObject1;
//            JToken var_JToken2;
//            JArray resultArray3;
//            JToken source4;
//            RuntimeContext.SetVariable(argContext, "src", ((Object)(this.srv_0.Call("service_0", new object[] {
//                            ((Object)(argContext)),
//                            ((Object)("..\\..\\gits\\ref_list_temps.json"))}))));
//            var_JObject1 = new JObject();
//            var_JToken2 = RuntimeContext.Translate(argContext, "@@src", this.srv_1);
//            resultArray3 = new JArray();
//            source4 = RuntimeContext.GetContentByJPath(argContext, var_JToken2, "$");
//            if ((source4.GetType() == typeof(JArray)))
//            {
//                JArray var_JArray5;
//                Int32 var_Int326;
//                var_JArray5 = ((JArray)(source4));
//                var_Int326 = 0;
//                while ((var_Int326 < var_JArray5.Count))
//                {
//                    JToken currentArrayItem9;
//                    Boolean var_Boolean10;
//                    currentArrayItem9 = var_JArray5[var_Int326];
//                    var_Boolean10 = RuntimeContext.ConvertToBool(RuntimeContext.GetContentFromService(argContext, RuntimeContext.GetContentByJPath(argContext, currentArrayItem9, "$.Object"), this.srv_2.Call("service_1", new object[0])));
//                    if ((var_Boolean10 == true))
//                    {
//                        JObject var_JObject11;
//                        JArray resultArray12;
//                        JToken source13;
//                        RuntimeContext.SetVariable(argContext, "object", ((Object)(RuntimeContext.GetContentByJPath(argContext, currentArrayItem9, "$.Object"))));
//                        var_JObject11 = new JObject();
//                        RuntimeContext.AddProperty(var_JObject11, new JProperty("datas", RuntimeContext.Translate(argContext, "@@object", this.srv_3)));
//                        resultArray12 = new JArray();
//                        source13 = RuntimeContext.GetContentFromService(argContext, currentArrayItem9, this.srv_4.Call("service_2", new object[] {
//                                        ((Object)(RuntimeContext.Translate(argContext, "@@src", this.srv_5))),
//                                        ((Object)(InternalConverters.ToString(RuntimeContext.Translate(argContext, "$[?(@.Object==\'@@object\')]", this.srv_6))))}));
//                        if ((source13.GetType() == typeof(JArray)))
//                        {
//                            JArray var_JArray14;
//                            Int32 var_Int3215;
//                            var_JArray14 = ((JArray)(source13));
//                            var_Int3215 = 0;
//                            while ((var_Int3215 < var_JArray14.Count))
//                            {
//                                JToken currentArrayItem18;
//                                JObject var_JObject19;
//                                JToken var_JToken20;
//                                currentArrayItem18 = var_JArray14[var_Int3215];
//                                var_JObject19 = new JObject();
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("g", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.Global")));
//                                var_JToken20 = ((JToken)(null));
//                                if ((((Boolean)(((JValue)(RuntimeContext.EvaluateBinaryOperator(argContext, RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.Global"), , InternalConverters.ToJToken("Non")))).Value)) == true))
//                                {
//                                    var_JToken20 = JToken.op_Implicit(false);
//                                }
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("Global", var_JToken20));
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("Default_Label", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.Default_Label")));
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("FKEY", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.FKEY")));
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("Label_FR", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.Label_FR")));
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("Property_name", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.Property_name")));
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("Commentaire", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.Commentaire")));
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("Legacy_Key_CRM", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.Legacy_Key_CRM")));
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("Legacy_Key_DBPickup", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.Legacy_Key_DBPickup")));
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("Formation", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.Formation")));
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("Impact_Usage_Mobilite_", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.Impact_Usage_Mobilite_")));
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("Definition", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.Definition")));
//                                RuntimeContext.AddProperty(var_JObject19, new JProperty("row", RuntimeContext.GetContentByJPath(argContext, currentArrayItem18, "$.$row")));
//                                resultArray12.Add(((Object)(var_JObject19)));
//                                var varParam_0_0 = var_Int3215;
//                                var_Int3215 = this.Increment(varParam_0_0);
//                            }
//                        }
//                        RuntimeContext.AddProperty(var_JObject11, new JProperty("items", resultArray12));
//                        RuntimeContext.DelVariable(argContext, "object");
//                        resultArray3.Add(((Object)(var_JObject11)));
//                    }
//                    var varParam_0_1 = var_Int326;
//                    var_Int326 = this.Increment(varParam_0_1);
//                }
//            }
//            RuntimeContext.AddProperty(var_JObject1, new JProperty("Items", resultArray3));
//            RuntimeContext.DelVariable(argContext, "src");
//            this.srv_0.Reset();
//            this.srv_2.Reset();
//            this.srv_4.Reset();
//            return var_JObject1;
//        }

//        private Boolean Not(bool self)
//        {
//            if (self)
//            {
//                return false;
//            }
//            else
//            {
//                return true;
//            }
//        }

//        private Int32 Increment(int self)
//        {
//            self = (self + 1);
//            return self;
//        }

//        private Int32 Decrement(int self)
//        {
//            self = (self - 1);
//            return self;
//        }
//    }
//}
