//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ElasticParser.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Bb.Elastic.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ElasticParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IElasticParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.parse"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParse([NotNull] ElasticParser.ParseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.error"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitError([NotNull] ElasticParser.ErrorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.sql_stmt_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSql_stmt_list([NotNull] ElasticParser.Sql_stmt_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.sql_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSql_stmt([NotNull] ElasticParser.Sql_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.where_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhere_stmt([NotNull] ElasticParser.Where_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.indexed_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndexed_column([NotNull] ElasticParser.Indexed_columnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.create_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_table_stmt([NotNull] ElasticParser.Create_table_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.column_def"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_def([NotNull] ElasticParser.Column_defContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name([NotNull] ElasticParser.Type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.column_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_constraint([NotNull] ElasticParser.Column_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.signed_number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSigned_number([NotNull] ElasticParser.Signed_numberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.table_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_constraint([NotNull] ElasticParser.Table_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.foreign_key_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeign_key_clause([NotNull] ElasticParser.Foreign_key_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.conflict_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConflict_clause([NotNull] ElasticParser.Conflict_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.create_view_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_view_stmt([NotNull] ElasticParser.Create_view_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.create_virtual_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCreate_virtual_table_stmt([NotNull] ElasticParser.Create_virtual_table_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.with_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWith_clause([NotNull] ElasticParser.With_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.cte_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCte_table_name([NotNull] ElasticParser.Cte_table_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.recursive_cte"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecursive_cte([NotNull] ElasticParser.Recursive_cteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.common_table_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommon_table_expression([NotNull] ElasticParser.Common_table_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] ElasticParser.ExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.call_function_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCall_function_expr([NotNull] ElasticParser.Call_function_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.in_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIn_expr([NotNull] ElasticParser.In_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.case_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_expression([NotNull] ElasticParser.Case_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.case_when"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_when([NotNull] ElasticParser.Case_whenContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.case_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_expr([NotNull] ElasticParser.Case_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.case_else_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_else_expr([NotNull] ElasticParser.Case_else_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.exists_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExists_expr([NotNull] ElasticParser.Exists_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.nullable_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullable_expr([NotNull] ElasticParser.Nullable_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.binary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_operator([NotNull] ElasticParser.Binary_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.like_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLike_operator([NotNull] ElasticParser.Like_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.raise_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRaise_function([NotNull] ElasticParser.Raise_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.literal_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteral_value([NotNull] ElasticParser.Literal_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.insert_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInsert_stmt([NotNull] ElasticParser.Insert_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.upsert_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUpsert_clause([NotNull] ElasticParser.Upsert_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.select_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_stmt([NotNull] ElasticParser.Select_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.compound"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound([NotNull] ElasticParser.CompoundContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.join_clauses"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_clauses([NotNull] ElasticParser.Join_clausesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.join_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_clause([NotNull] ElasticParser.Join_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.select_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelect_core([NotNull] ElasticParser.Select_coreContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.value_list_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_list_stmt([NotNull] ElasticParser.Value_list_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.group_by_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup_by_stmt([NotNull] ElasticParser.Group_by_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.having_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHaving_stmt([NotNull] ElasticParser.Having_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.window_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_stmt([NotNull] ElasticParser.Window_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.expr_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr_list([NotNull] ElasticParser.Expr_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.table_or_subquery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_or_subquery([NotNull] ElasticParser.Table_or_subqueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.subquery_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubquery_table([NotNull] ElasticParser.Subquery_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.result_column"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitResult_column([NotNull] ElasticParser.Result_columnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.join_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_operator([NotNull] ElasticParser.Join_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.join_constraint"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJoin_constraint([NotNull] ElasticParser.Join_constraintContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.compound_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_operator([NotNull] ElasticParser.Compound_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.column_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_name_list([NotNull] ElasticParser.Column_name_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.filter_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilter_clause([NotNull] ElasticParser.Filter_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.window_defn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_defn([NotNull] ElasticParser.Window_defnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.over_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOver_clause([NotNull] ElasticParser.Over_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.frame_spec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_spec([NotNull] ElasticParser.Frame_specContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.frame_clause"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_clause([NotNull] ElasticParser.Frame_clauseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.common_table_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommon_table_stmt([NotNull] ElasticParser.Common_table_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.order_by_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder_by_stmt([NotNull] ElasticParser.Order_by_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.limit_stmts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLimit_stmts([NotNull] ElasticParser.Limit_stmtsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.limit_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLimit_stmt([NotNull] ElasticParser.Limit_stmtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.ordering_term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrdering_term([NotNull] ElasticParser.Ordering_termContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.asc_desc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAsc_desc([NotNull] ElasticParser.Asc_descContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.frame_left"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_left([NotNull] ElasticParser.Frame_leftContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.frame_right"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_right([NotNull] ElasticParser.Frame_rightContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.frame_single"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFrame_single([NotNull] ElasticParser.Frame_singleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.window_function"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_function([NotNull] ElasticParser.Window_functionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.offset"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOffset([NotNull] ElasticParser.OffsetContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.default_value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDefault_value([NotNull] ElasticParser.Default_valueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.partition_by"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPartition_by([NotNull] ElasticParser.Partition_byContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.order_by_expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder_by_expr([NotNull] ElasticParser.Order_by_exprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.order_by_expr_asc_desc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrder_by_expr_asc_desc([NotNull] ElasticParser.Order_by_expr_asc_descContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.initial_select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitial_select([NotNull] ElasticParser.Initial_selectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.recursive_select"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecursive_select([NotNull] ElasticParser.Recursive_selectContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_operator([NotNull] ElasticParser.Unary_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.error_message"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitError_message([NotNull] ElasticParser.Error_messageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.module_argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule_argument([NotNull] ElasticParser.Module_argumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.column_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_alias([NotNull] ElasticParser.Column_aliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.keyword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKeyword([NotNull] ElasticParser.KeywordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] ElasticParser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.full_function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFull_function_name([NotNull] ElasticParser.Full_function_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_name([NotNull] ElasticParser.Function_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.schema_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSchema_name([NotNull] ElasticParser.Schema_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_name([NotNull] ElasticParser.Table_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.full_table_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFull_table_name([NotNull] ElasticParser.Full_table_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.fullname"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFullname([NotNull] ElasticParser.FullnameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.column_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColumn_name([NotNull] ElasticParser.Column_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.collation_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCollation_name([NotNull] ElasticParser.Collation_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.foreign_table"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForeign_table([NotNull] ElasticParser.Foreign_tableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.index_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIndex_name([NotNull] ElasticParser.Index_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.view_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitView_name([NotNull] ElasticParser.View_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.module_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModule_name([NotNull] ElasticParser.Module_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.table_alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_alias([NotNull] ElasticParser.Table_aliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.window_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWindow_name([NotNull] ElasticParser.Window_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.alias"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlias([NotNull] ElasticParser.AliasContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.base_window_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_window_name([NotNull] ElasticParser.Base_window_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.simple_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_func([NotNull] ElasticParser.Simple_funcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.aggregate_func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAggregate_func([NotNull] ElasticParser.Aggregate_funcContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.table_function_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTable_function_name([NotNull] ElasticParser.Table_function_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ElasticParser.any_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAny_name([NotNull] ElasticParser.Any_nameContext context);
}
} // namespace Bb.Elastic.Parser
