//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JsltParser.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Bb.Parsers.Intellisense.Jslt {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="JsltParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IJsltParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] JsltParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJson([NotNull] JsltParser.JsonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObj([NotNull] JsltParser.ObjContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPair([NotNull] JsltParser.PairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] JsltParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValue([NotNull] JsltParser.JsonValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueString([NotNull] JsltParser.JsonValueStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueNumber([NotNull] JsltParser.JsonValueNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueInteger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueInteger([NotNull] JsltParser.JsonValueIntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueBoolean([NotNull] JsltParser.JsonValueBooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueNull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueNull([NotNull] JsltParser.JsonValueNullContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonType([NotNull] JsltParser.JsonTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonLtOperation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonLtOperation([NotNull] JsltParser.JsonLtOperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonLtItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonLtItem([NotNull] JsltParser.JsonLtItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.operation"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperation([NotNull] JsltParser.OperationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonfunctionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonfunctionCall([NotNull] JsltParser.JsonfunctionCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonfunctionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonfunctionName([NotNull] JsltParser.JsonfunctionNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueList([NotNull] JsltParser.JsonValueListContext context);
}
} // namespace Bb.Parsers.Intellisense.Jslt
