//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JsltParser.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Bb.Json.Jslt.Parser {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class JsltParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SUBSCRIPT=1, WILDCARD_SUBSCRIPT=2, CURRENT_VALUE=3, COLON=4, URI=5, TIME=6, 
		DATETIME=7, WHEN=8, CASE=9, DEFAULT=10, EQ=11, NE=12, GT=13, LT=14, LE=15, 
		GE=16, NT=17, PLUS=18, MINUS=19, DIVID=20, MODULO=21, POWER=22, AND=23, 
		OR=24, AND_EXCLUSIVE=25, OR_EXCLUSIVE=26, CHAIN=27, TRUE=28, FALSE=29, 
		NULL=30, BRACE_LEFT=31, BRACE_RIGHT=32, BRACKET_LEFT=33, BRACKET_RIGHT=34, 
		COMMA=35, PAREN_LEFT=36, PAREN_RIGHT=37, STRING=38, MULTI_LINE_COMMENT=39, 
		CODE_STRING=40, QUOTE_CODE_STRING=41, NUMBER=42, INT=43, WS=44, ID=45;
	public const int
		RULE_script = 0, RULE_json = 1, RULE_obj = 2, RULE_pair = 3, RULE_array = 4, 
		RULE_jsonValue = 5, RULE_jsonValueString = 6, RULE_jsonValueCodeString = 7, 
		RULE_jsonValueNumber = 8, RULE_jsonValueInteger = 9, RULE_jsonValueBoolean = 10, 
		RULE_jsonValueNull = 11, RULE_jsonType = 12, RULE_jsonLtOperation = 13, 
		RULE_jsonLtItem = 14, RULE_operation = 15, RULE_jsonfunctionCall = 16, 
		RULE_jsonValueList = 17, RULE_jsonWhen = 18, RULE_jsonCase = 19, RULE_jsonDefaultCase = 20, 
		RULE_jsonWhenExpression = 21;
	public static readonly string[] ruleNames = {
		"script", "json", "obj", "pair", "array", "jsonValue", "jsonValueString", 
		"jsonValueCodeString", "jsonValueNumber", "jsonValueInteger", "jsonValueBoolean", 
		"jsonValueNull", "jsonType", "jsonLtOperation", "jsonLtItem", "operation", 
		"jsonfunctionCall", "jsonValueList", "jsonWhen", "jsonCase", "jsonDefaultCase", 
		"jsonWhenExpression"
	};

	private static readonly string[] _LiteralNames = {
		null, "'.'", "'*'", "'@'", "':'", "'uri'", "'time'", "'datetime'", "'when'", 
		"'case'", "'default'", "'=='", "'!='", "'>'", "'<'", "'<='", "'>='", "'!'", 
		"'+'", "'-'", "'/'", "'%'", "'^'", "'&'", "'|'", "'&&'", "'||'", "'->'", 
		"'true'", "'false'", "'null'", "'{'", "'}'", "'['", "']'", "','", "'('", 
		"')'", null, null, null, "'''''"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SUBSCRIPT", "WILDCARD_SUBSCRIPT", "CURRENT_VALUE", "COLON", "URI", 
		"TIME", "DATETIME", "WHEN", "CASE", "DEFAULT", "EQ", "NE", "GT", "LT", 
		"LE", "GE", "NT", "PLUS", "MINUS", "DIVID", "MODULO", "POWER", "AND", 
		"OR", "AND_EXCLUSIVE", "OR_EXCLUSIVE", "CHAIN", "TRUE", "FALSE", "NULL", 
		"BRACE_LEFT", "BRACE_RIGHT", "BRACKET_LEFT", "BRACKET_RIGHT", "COMMA", 
		"PAREN_LEFT", "PAREN_RIGHT", "STRING", "MULTI_LINE_COMMENT", "CODE_STRING", 
		"QUOTE_CODE_STRING", "NUMBER", "INT", "WS", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JsltParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static JsltParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public JsltParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public JsltParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}
	public partial class ScriptContext : ParserRuleContext {
		public JsonContext json() {
			return GetRuleContext<JsonContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(JsltParser.Eof, 0); }
		public ScriptContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_script; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScript(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScriptContext script() {
		ScriptContext _localctx = new ScriptContext(Context, State);
		EnterRule(_localctx, 0, RULE_script);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 44; json();
			State = 45; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonContext : ParserRuleContext {
		public JsonValueContext jsonValue() {
			return GetRuleContext<JsonValueContext>(0);
		}
		public JsonContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_json; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJson(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonContext json() {
		JsonContext _localctx = new JsonContext(Context, State);
		EnterRule(_localctx, 2, RULE_json);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 47; jsonValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ObjContext : ParserRuleContext {
		public ITerminalNode BRACE_LEFT() { return GetToken(JsltParser.BRACE_LEFT, 0); }
		public PairContext[] pair() {
			return GetRuleContexts<PairContext>();
		}
		public PairContext pair(int i) {
			return GetRuleContext<PairContext>(i);
		}
		public ITerminalNode BRACE_RIGHT() { return GetToken(JsltParser.BRACE_RIGHT, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(JsltParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(JsltParser.COMMA, i);
		}
		public ObjContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_obj; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitObj(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ObjContext obj() {
		ObjContext _localctx = new ObjContext(Context, State);
		EnterRule(_localctx, 4, RULE_obj);
		int _la;
		try {
			State = 62;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 49; Match(BRACE_LEFT);
				State = 50; pair();
				State = 55;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 51; Match(COMMA);
					State = 52; pair();
					}
					}
					State = 57;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 58; Match(BRACE_RIGHT);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 60; Match(BRACE_LEFT);
				State = 61; Match(BRACE_RIGHT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PairContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(JsltParser.STRING, 0); }
		public ITerminalNode COLON() { return GetToken(JsltParser.COLON, 0); }
		public JsonValueContext jsonValue() {
			return GetRuleContext<JsonValueContext>(0);
		}
		public PairContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pair; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPair(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PairContext pair() {
		PairContext _localctx = new PairContext(Context, State);
		EnterRule(_localctx, 6, RULE_pair);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 64; Match(STRING);
			State = 65; Match(COLON);
			State = 66; jsonValue();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayContext : ParserRuleContext {
		public ITerminalNode BRACKET_LEFT() { return GetToken(JsltParser.BRACKET_LEFT, 0); }
		public JsonValueContext[] jsonValue() {
			return GetRuleContexts<JsonValueContext>();
		}
		public JsonValueContext jsonValue(int i) {
			return GetRuleContext<JsonValueContext>(i);
		}
		public ITerminalNode BRACKET_RIGHT() { return GetToken(JsltParser.BRACKET_RIGHT, 0); }
		public ITerminalNode[] COMMA() { return GetTokens(JsltParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(JsltParser.COMMA, i);
		}
		public ArrayContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_array; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArray(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayContext array() {
		ArrayContext _localctx = new ArrayContext(Context, State);
		EnterRule(_localctx, 8, RULE_array);
		int _la;
		try {
			State = 81;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 68; Match(BRACKET_LEFT);
				State = 69; jsonValue();
				State = 74;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 70; Match(COMMA);
					State = 71; jsonValue();
					}
					}
					State = 76;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 77; Match(BRACKET_RIGHT);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 79; Match(BRACKET_LEFT);
				State = 80; Match(BRACKET_RIGHT);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonValueContext : ParserRuleContext {
		public ObjContext obj() {
			return GetRuleContext<ObjContext>(0);
		}
		public ArrayContext array() {
			return GetRuleContext<ArrayContext>(0);
		}
		public JsonLtOperationContext jsonLtOperation() {
			return GetRuleContext<JsonLtOperationContext>(0);
		}
		public JsonValueCodeStringContext jsonValueCodeString() {
			return GetRuleContext<JsonValueCodeStringContext>(0);
		}
		public JsonValueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonValue; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonValue(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonValueContext jsonValue() {
		JsonValueContext _localctx = new JsonValueContext(Context, State);
		EnterRule(_localctx, 10, RULE_jsonValue);
		try {
			State = 87;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case BRACE_LEFT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 83; obj();
				}
				break;
			case BRACKET_LEFT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 84; array();
				}
				break;
			case SUBSCRIPT:
			case CURRENT_VALUE:
			case NT:
			case TRUE:
			case FALSE:
			case NULL:
			case PAREN_LEFT:
			case STRING:
			case NUMBER:
			case INT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 85; jsonLtOperation();
				}
				break;
			case CODE_STRING:
				EnterOuterAlt(_localctx, 4);
				{
				State = 86; jsonValueCodeString();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonValueStringContext : ParserRuleContext {
		public ITerminalNode STRING() { return GetToken(JsltParser.STRING, 0); }
		public JsonValueStringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonValueString; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonValueString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonValueStringContext jsonValueString() {
		JsonValueStringContext _localctx = new JsonValueStringContext(Context, State);
		EnterRule(_localctx, 12, RULE_jsonValueString);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 89; Match(STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonValueCodeStringContext : ParserRuleContext {
		public ITerminalNode CODE_STRING() { return GetToken(JsltParser.CODE_STRING, 0); }
		public JsonValueCodeStringContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonValueCodeString; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonValueCodeString(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonValueCodeStringContext jsonValueCodeString() {
		JsonValueCodeStringContext _localctx = new JsonValueCodeStringContext(Context, State);
		EnterRule(_localctx, 14, RULE_jsonValueCodeString);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91; Match(CODE_STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonValueNumberContext : ParserRuleContext {
		public ITerminalNode NUMBER() { return GetToken(JsltParser.NUMBER, 0); }
		public JsonValueNumberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonValueNumber; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonValueNumber(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonValueNumberContext jsonValueNumber() {
		JsonValueNumberContext _localctx = new JsonValueNumberContext(Context, State);
		EnterRule(_localctx, 16, RULE_jsonValueNumber);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93; Match(NUMBER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonValueIntegerContext : ParserRuleContext {
		public ITerminalNode INT() { return GetToken(JsltParser.INT, 0); }
		public JsonValueIntegerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonValueInteger; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonValueInteger(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonValueIntegerContext jsonValueInteger() {
		JsonValueIntegerContext _localctx = new JsonValueIntegerContext(Context, State);
		EnterRule(_localctx, 18, RULE_jsonValueInteger);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 95; Match(INT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonValueBooleanContext : ParserRuleContext {
		public ITerminalNode TRUE() { return GetToken(JsltParser.TRUE, 0); }
		public ITerminalNode FALSE() { return GetToken(JsltParser.FALSE, 0); }
		public JsonValueBooleanContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonValueBoolean; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonValueBoolean(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonValueBooleanContext jsonValueBoolean() {
		JsonValueBooleanContext _localctx = new JsonValueBooleanContext(Context, State);
		EnterRule(_localctx, 20, RULE_jsonValueBoolean);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 97;
			_la = TokenStream.LA(1);
			if ( !(_la==TRUE || _la==FALSE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonValueNullContext : ParserRuleContext {
		public ITerminalNode NULL() { return GetToken(JsltParser.NULL, 0); }
		public JsonValueNullContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonValueNull; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonValueNull(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonValueNullContext jsonValueNull() {
		JsonValueNullContext _localctx = new JsonValueNullContext(Context, State);
		EnterRule(_localctx, 22, RULE_jsonValueNull);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99; Match(NULL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonTypeContext : ParserRuleContext {
		public ITerminalNode CURRENT_VALUE() { return GetToken(JsltParser.CURRENT_VALUE, 0); }
		public ITerminalNode URI() { return GetToken(JsltParser.URI, 0); }
		public ITerminalNode TIME() { return GetToken(JsltParser.TIME, 0); }
		public ITerminalNode DATETIME() { return GetToken(JsltParser.DATETIME, 0); }
		public JsonTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonType; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonTypeContext jsonType() {
		JsonTypeContext _localctx = new JsonTypeContext(Context, State);
		EnterRule(_localctx, 24, RULE_jsonType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101; Match(CURRENT_VALUE);
			State = 102;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << URI) | (1L << TIME) | (1L << DATETIME))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonLtOperationContext : ParserRuleContext {
		public JsonLtItemContext jsonLtItem() {
			return GetRuleContext<JsonLtItemContext>(0);
		}
		public ITerminalNode NT() { return GetToken(JsltParser.NT, 0); }
		public OperationContext operation() {
			return GetRuleContext<OperationContext>(0);
		}
		public JsonLtOperationContext jsonLtOperation() {
			return GetRuleContext<JsonLtOperationContext>(0);
		}
		public ITerminalNode PAREN_LEFT() { return GetToken(JsltParser.PAREN_LEFT, 0); }
		public ITerminalNode PAREN_RIGHT() { return GetToken(JsltParser.PAREN_RIGHT, 0); }
		public JsonLtOperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonLtOperation; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonLtOperation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonLtOperationContext jsonLtOperation() {
		JsonLtOperationContext _localctx = new JsonLtOperationContext(Context, State);
		EnterRule(_localctx, 26, RULE_jsonLtOperation);
		int _la;
		try {
			State = 117;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case SUBSCRIPT:
			case CURRENT_VALUE:
			case NT:
			case TRUE:
			case FALSE:
			case NULL:
			case STRING:
			case NUMBER:
			case INT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 105;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==NT) {
					{
					State = 104; Match(NT);
					}
				}

				State = 107; jsonLtItem();
				State = 111;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << WILDCARD_SUBSCRIPT) | (1L << EQ) | (1L << NE) | (1L << GT) | (1L << LT) | (1L << LE) | (1L << GE) | (1L << PLUS) | (1L << MINUS) | (1L << DIVID) | (1L << MODULO) | (1L << POWER) | (1L << AND) | (1L << OR) | (1L << AND_EXCLUSIVE) | (1L << OR_EXCLUSIVE) | (1L << CHAIN))) != 0)) {
					{
					State = 108; operation();
					State = 109; jsonLtOperation();
					}
				}

				}
				break;
			case PAREN_LEFT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 113; Match(PAREN_LEFT);
				State = 114; jsonLtOperation();
				State = 115; Match(PAREN_RIGHT);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonLtItemContext : ParserRuleContext {
		public JsonfunctionCallContext jsonfunctionCall() {
			return GetRuleContext<JsonfunctionCallContext>(0);
		}
		public JsonWhenContext jsonWhen() {
			return GetRuleContext<JsonWhenContext>(0);
		}
		public JsonValueBooleanContext jsonValueBoolean() {
			return GetRuleContext<JsonValueBooleanContext>(0);
		}
		public JsonValueStringContext jsonValueString() {
			return GetRuleContext<JsonValueStringContext>(0);
		}
		public JsonValueIntegerContext jsonValueInteger() {
			return GetRuleContext<JsonValueIntegerContext>(0);
		}
		public JsonValueNumberContext jsonValueNumber() {
			return GetRuleContext<JsonValueNumberContext>(0);
		}
		public JsonValueNullContext jsonValueNull() {
			return GetRuleContext<JsonValueNullContext>(0);
		}
		public JsonTypeContext jsonType() {
			return GetRuleContext<JsonTypeContext>(0);
		}
		public JsonLtItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonLtItem; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonLtItem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonLtItemContext jsonLtItem() {
		JsonLtItemContext _localctx = new JsonLtItemContext(Context, State);
		EnterRule(_localctx, 28, RULE_jsonLtItem);
		try {
			State = 127;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 119; jsonfunctionCall();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 120; jsonWhen();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 121; jsonValueBoolean();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 122; jsonValueString();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 123; jsonValueInteger();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 124; jsonValueNumber();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 125; jsonValueNull();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 126; jsonType();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OperationContext : ParserRuleContext {
		public ITerminalNode EQ() { return GetToken(JsltParser.EQ, 0); }
		public ITerminalNode GE() { return GetToken(JsltParser.GE, 0); }
		public ITerminalNode GT() { return GetToken(JsltParser.GT, 0); }
		public ITerminalNode LE() { return GetToken(JsltParser.LE, 0); }
		public ITerminalNode LT() { return GetToken(JsltParser.LT, 0); }
		public ITerminalNode NE() { return GetToken(JsltParser.NE, 0); }
		public ITerminalNode PLUS() { return GetToken(JsltParser.PLUS, 0); }
		public ITerminalNode MINUS() { return GetToken(JsltParser.MINUS, 0); }
		public ITerminalNode DIVID() { return GetToken(JsltParser.DIVID, 0); }
		public ITerminalNode MODULO() { return GetToken(JsltParser.MODULO, 0); }
		public ITerminalNode WILDCARD_SUBSCRIPT() { return GetToken(JsltParser.WILDCARD_SUBSCRIPT, 0); }
		public ITerminalNode POWER() { return GetToken(JsltParser.POWER, 0); }
		public ITerminalNode CHAIN() { return GetToken(JsltParser.CHAIN, 0); }
		public ITerminalNode AND() { return GetToken(JsltParser.AND, 0); }
		public ITerminalNode OR() { return GetToken(JsltParser.OR, 0); }
		public ITerminalNode AND_EXCLUSIVE() { return GetToken(JsltParser.AND_EXCLUSIVE, 0); }
		public ITerminalNode OR_EXCLUSIVE() { return GetToken(JsltParser.OR_EXCLUSIVE, 0); }
		public OperationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operation; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperation(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OperationContext operation() {
		OperationContext _localctx = new OperationContext(Context, State);
		EnterRule(_localctx, 30, RULE_operation);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 129;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << WILDCARD_SUBSCRIPT) | (1L << EQ) | (1L << NE) | (1L << GT) | (1L << LT) | (1L << LE) | (1L << GE) | (1L << PLUS) | (1L << MINUS) | (1L << DIVID) | (1L << MODULO) | (1L << POWER) | (1L << AND) | (1L << OR) | (1L << AND_EXCLUSIVE) | (1L << OR_EXCLUSIVE) | (1L << CHAIN))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonfunctionCallContext : ParserRuleContext {
		public ITerminalNode SUBSCRIPT() { return GetToken(JsltParser.SUBSCRIPT, 0); }
		public ITerminalNode ID() { return GetToken(JsltParser.ID, 0); }
		public ITerminalNode PAREN_LEFT() { return GetToken(JsltParser.PAREN_LEFT, 0); }
		public ITerminalNode PAREN_RIGHT() { return GetToken(JsltParser.PAREN_RIGHT, 0); }
		public JsonValueListContext jsonValueList() {
			return GetRuleContext<JsonValueListContext>(0);
		}
		public JsonfunctionCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonfunctionCall; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonfunctionCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonfunctionCallContext jsonfunctionCall() {
		JsonfunctionCallContext _localctx = new JsonfunctionCallContext(Context, State);
		EnterRule(_localctx, 32, RULE_jsonfunctionCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 131; Match(SUBSCRIPT);
			State = 132; Match(ID);
			State = 133; Match(PAREN_LEFT);
			State = 135;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << SUBSCRIPT) | (1L << CURRENT_VALUE) | (1L << NT) | (1L << TRUE) | (1L << FALSE) | (1L << NULL) | (1L << BRACE_LEFT) | (1L << BRACKET_LEFT) | (1L << PAREN_LEFT) | (1L << STRING) | (1L << CODE_STRING) | (1L << NUMBER) | (1L << INT))) != 0)) {
				{
				State = 134; jsonValueList();
				}
			}

			State = 137; Match(PAREN_RIGHT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonValueListContext : ParserRuleContext {
		public JsonValueContext[] jsonValue() {
			return GetRuleContexts<JsonValueContext>();
		}
		public JsonValueContext jsonValue(int i) {
			return GetRuleContext<JsonValueContext>(i);
		}
		public ITerminalNode[] COMMA() { return GetTokens(JsltParser.COMMA); }
		public ITerminalNode COMMA(int i) {
			return GetToken(JsltParser.COMMA, i);
		}
		public JsonValueListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonValueList; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonValueList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonValueListContext jsonValueList() {
		JsonValueListContext _localctx = new JsonValueListContext(Context, State);
		EnterRule(_localctx, 34, RULE_jsonValueList);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 139; jsonValue();
			State = 144;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==COMMA) {
				{
				{
				State = 140; Match(COMMA);
				State = 141; jsonValue();
				}
				}
				State = 146;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonWhenContext : ParserRuleContext {
		public ITerminalNode SUBSCRIPT() { return GetToken(JsltParser.SUBSCRIPT, 0); }
		public ITerminalNode WHEN() { return GetToken(JsltParser.WHEN, 0); }
		public JsonWhenExpressionContext jsonWhenExpression() {
			return GetRuleContext<JsonWhenExpressionContext>(0);
		}
		public JsonCaseContext[] jsonCase() {
			return GetRuleContexts<JsonCaseContext>();
		}
		public JsonCaseContext jsonCase(int i) {
			return GetRuleContext<JsonCaseContext>(i);
		}
		public JsonDefaultCaseContext jsonDefaultCase() {
			return GetRuleContext<JsonDefaultCaseContext>(0);
		}
		public JsonWhenContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonWhen; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonWhen(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonWhenContext jsonWhen() {
		JsonWhenContext _localctx = new JsonWhenContext(Context, State);
		EnterRule(_localctx, 36, RULE_jsonWhen);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 147; Match(SUBSCRIPT);
			State = 148; Match(WHEN);
			State = 149; jsonWhenExpression();
			State = 151;
			ErrorHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 150; jsonCase();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 153;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,11,Context);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			State = 156;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==DEFAULT) {
				{
				State = 155; jsonDefaultCase();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonCaseContext : ParserRuleContext {
		public ITerminalNode CASE() { return GetToken(JsltParser.CASE, 0); }
		public JsonWhenExpressionContext jsonWhenExpression() {
			return GetRuleContext<JsonWhenExpressionContext>(0);
		}
		public ITerminalNode COLON() { return GetToken(JsltParser.COLON, 0); }
		public ITerminalNode BRACE_LEFT() { return GetToken(JsltParser.BRACE_LEFT, 0); }
		public JsonValueContext jsonValue() {
			return GetRuleContext<JsonValueContext>(0);
		}
		public ITerminalNode BRACE_RIGHT() { return GetToken(JsltParser.BRACE_RIGHT, 0); }
		public JsonDefaultCaseContext jsonDefaultCase() {
			return GetRuleContext<JsonDefaultCaseContext>(0);
		}
		public JsonCaseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonCase; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonCase(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonCaseContext jsonCase() {
		JsonCaseContext _localctx = new JsonCaseContext(Context, State);
		EnterRule(_localctx, 38, RULE_jsonCase);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 158; Match(CASE);
			State = 159; jsonWhenExpression();
			State = 160; Match(COLON);
			State = 161; Match(BRACE_LEFT);
			State = 162; jsonValue();
			State = 163; Match(BRACE_RIGHT);
			State = 165;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 164; jsonDefaultCase();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonDefaultCaseContext : ParserRuleContext {
		public ITerminalNode DEFAULT() { return GetToken(JsltParser.DEFAULT, 0); }
		public ITerminalNode COLON() { return GetToken(JsltParser.COLON, 0); }
		public ITerminalNode BRACE_LEFT() { return GetToken(JsltParser.BRACE_LEFT, 0); }
		public JsonValueContext jsonValue() {
			return GetRuleContext<JsonValueContext>(0);
		}
		public ITerminalNode BRACE_RIGHT() { return GetToken(JsltParser.BRACE_RIGHT, 0); }
		public JsonDefaultCaseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonDefaultCase; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonDefaultCase(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonDefaultCaseContext jsonDefaultCase() {
		JsonDefaultCaseContext _localctx = new JsonDefaultCaseContext(Context, State);
		EnterRule(_localctx, 40, RULE_jsonDefaultCase);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167; Match(DEFAULT);
			State = 168; Match(COLON);
			State = 169; Match(BRACE_LEFT);
			State = 170; jsonValue();
			State = 171; Match(BRACE_RIGHT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JsonWhenExpressionContext : ParserRuleContext {
		public JsonValueBooleanContext jsonValueBoolean() {
			return GetRuleContext<JsonValueBooleanContext>(0);
		}
		public JsonValueStringContext jsonValueString() {
			return GetRuleContext<JsonValueStringContext>(0);
		}
		public JsonValueIntegerContext jsonValueInteger() {
			return GetRuleContext<JsonValueIntegerContext>(0);
		}
		public JsonValueNumberContext jsonValueNumber() {
			return GetRuleContext<JsonValueNumberContext>(0);
		}
		public JsonValueNullContext jsonValueNull() {
			return GetRuleContext<JsonValueNullContext>(0);
		}
		public JsonLtOperationContext jsonLtOperation() {
			return GetRuleContext<JsonLtOperationContext>(0);
		}
		public JsonWhenExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jsonWhenExpression; } }
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IJsltParserVisitor<TResult> typedVisitor = visitor as IJsltParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJsonWhenExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JsonWhenExpressionContext jsonWhenExpression() {
		JsonWhenExpressionContext _localctx = new JsonWhenExpressionContext(Context, State);
		EnterRule(_localctx, 42, RULE_jsonWhenExpression);
		try {
			State = 179;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,14,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 173; jsonValueBoolean();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 174; jsonValueString();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 175; jsonValueInteger();
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 176; jsonValueNumber();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 177; jsonValueNull();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 178; jsonLtOperation();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '/', '\xB8', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', '\x38', '\n', '\x4', '\f', 
		'\x4', '\xE', '\x4', ';', '\v', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x5', '\x4', '\x41', '\n', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\x6', '\a', '\x6', 'K', '\n', '\x6', '\f', '\x6', 
		'\xE', '\x6', 'N', '\v', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x5', '\x6', 'T', '\n', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\a', '\x3', '\a', '\x5', '\a', 'Z', '\n', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\t', '\x3', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x5', '\xF', 'l', '\n', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x5', 
		'\xF', 'r', '\n', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x5', '\xF', 'x', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x5', '\x10', '\x82', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x5', '\x12', 
		'\x8A', '\n', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\a', '\x13', '\x91', '\n', '\x13', '\f', '\x13', 
		'\xE', '\x13', '\x94', '\v', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x6', '\x14', '\x9A', '\n', '\x14', '\r', '\x14', 
		'\xE', '\x14', '\x9B', '\x3', '\x14', '\x5', '\x14', '\x9F', '\n', '\x14', 
		'\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', 
		'\x3', '\x15', '\x3', '\x15', '\x5', '\x15', '\xA8', '\n', '\x15', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x17', '\x5', '\x17', '\xB6', '\n', '\x17', '\x3', '\x17', 
		'\x2', '\x2', '\x18', '\x2', '\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', 
		'\x12', '\x14', '\x16', '\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', 
		'&', '(', '*', ',', '\x2', '\x5', '\x3', '\x2', '\x1E', '\x1F', '\x3', 
		'\x2', '\a', '\t', '\x5', '\x2', '\x4', '\x4', '\r', '\x12', '\x14', '\x1D', 
		'\x2', '\xBC', '\x2', '.', '\x3', '\x2', '\x2', '\x2', '\x4', '\x31', 
		'\x3', '\x2', '\x2', '\x2', '\x6', '@', '\x3', '\x2', '\x2', '\x2', '\b', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\n', 'S', '\x3', '\x2', '\x2', '\x2', 
		'\f', 'Y', '\x3', '\x2', '\x2', '\x2', '\xE', '[', '\x3', '\x2', '\x2', 
		'\x2', '\x10', ']', '\x3', '\x2', '\x2', '\x2', '\x12', '_', '\x3', '\x2', 
		'\x2', '\x2', '\x14', '\x61', '\x3', '\x2', '\x2', '\x2', '\x16', '\x63', 
		'\x3', '\x2', '\x2', '\x2', '\x18', '\x65', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', 'g', '\x3', '\x2', '\x2', '\x2', '\x1C', 'w', '\x3', '\x2', '\x2', 
		'\x2', '\x1E', '\x81', '\x3', '\x2', '\x2', '\x2', ' ', '\x83', '\x3', 
		'\x2', '\x2', '\x2', '\"', '\x85', '\x3', '\x2', '\x2', '\x2', '$', '\x8D', 
		'\x3', '\x2', '\x2', '\x2', '&', '\x95', '\x3', '\x2', '\x2', '\x2', '(', 
		'\xA0', '\x3', '\x2', '\x2', '\x2', '*', '\xA9', '\x3', '\x2', '\x2', 
		'\x2', ',', '\xB5', '\x3', '\x2', '\x2', '\x2', '.', '/', '\x5', '\x4', 
		'\x3', '\x2', '/', '\x30', '\a', '\x2', '\x2', '\x3', '\x30', '\x3', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\x32', '\x5', '\f', '\a', '\x2', '\x32', 
		'\x5', '\x3', '\x2', '\x2', '\x2', '\x33', '\x34', '\a', '!', '\x2', '\x2', 
		'\x34', '\x39', '\x5', '\b', '\x5', '\x2', '\x35', '\x36', '\a', '%', 
		'\x2', '\x2', '\x36', '\x38', '\x5', '\b', '\x5', '\x2', '\x37', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x38', ';', '\x3', '\x2', '\x2', '\x2', '\x39', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x39', ':', '\x3', '\x2', '\x2', 
		'\x2', ':', '<', '\x3', '\x2', '\x2', '\x2', ';', '\x39', '\x3', '\x2', 
		'\x2', '\x2', '<', '=', '\a', '\"', '\x2', '\x2', '=', '\x41', '\x3', 
		'\x2', '\x2', '\x2', '>', '?', '\a', '!', '\x2', '\x2', '?', '\x41', '\a', 
		'\"', '\x2', '\x2', '@', '\x33', '\x3', '\x2', '\x2', '\x2', '@', '>', 
		'\x3', '\x2', '\x2', '\x2', '\x41', '\a', '\x3', '\x2', '\x2', '\x2', 
		'\x42', '\x43', '\a', '(', '\x2', '\x2', '\x43', '\x44', '\a', '\x6', 
		'\x2', '\x2', '\x44', '\x45', '\x5', '\f', '\a', '\x2', '\x45', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x46', 'G', '\a', '#', '\x2', '\x2', 'G', 
		'L', '\x5', '\f', '\a', '\x2', 'H', 'I', '\a', '%', '\x2', '\x2', 'I', 
		'K', '\x5', '\f', '\a', '\x2', 'J', 'H', '\x3', '\x2', '\x2', '\x2', 'K', 
		'N', '\x3', '\x2', '\x2', '\x2', 'L', 'J', '\x3', '\x2', '\x2', '\x2', 
		'L', 'M', '\x3', '\x2', '\x2', '\x2', 'M', 'O', '\x3', '\x2', '\x2', '\x2', 
		'N', 'L', '\x3', '\x2', '\x2', '\x2', 'O', 'P', '\a', '$', '\x2', '\x2', 
		'P', 'T', '\x3', '\x2', '\x2', '\x2', 'Q', 'R', '\a', '#', '\x2', '\x2', 
		'R', 'T', '\a', '$', '\x2', '\x2', 'S', '\x46', '\x3', '\x2', '\x2', '\x2', 
		'S', 'Q', '\x3', '\x2', '\x2', '\x2', 'T', '\v', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'Z', '\x5', '\x6', '\x4', '\x2', 'V', 'Z', '\x5', '\n', '\x6', 
		'\x2', 'W', 'Z', '\x5', '\x1C', '\xF', '\x2', 'X', 'Z', '\x5', '\x10', 
		'\t', '\x2', 'Y', 'U', '\x3', '\x2', '\x2', '\x2', 'Y', 'V', '\x3', '\x2', 
		'\x2', '\x2', 'Y', 'W', '\x3', '\x2', '\x2', '\x2', 'Y', 'X', '\x3', '\x2', 
		'\x2', '\x2', 'Z', '\r', '\x3', '\x2', '\x2', '\x2', '[', '\\', '\a', 
		'(', '\x2', '\x2', '\\', '\xF', '\x3', '\x2', '\x2', '\x2', ']', '^', 
		'\a', '*', '\x2', '\x2', '^', '\x11', '\x3', '\x2', '\x2', '\x2', '_', 
		'`', '\a', ',', '\x2', '\x2', '`', '\x13', '\x3', '\x2', '\x2', '\x2', 
		'\x61', '\x62', '\a', '-', '\x2', '\x2', '\x62', '\x15', '\x3', '\x2', 
		'\x2', '\x2', '\x63', '\x64', '\t', '\x2', '\x2', '\x2', '\x64', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x65', '\x66', '\a', ' ', '\x2', '\x2', '\x66', 
		'\x19', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\a', '\x5', '\x2', '\x2', 
		'h', 'i', '\t', '\x3', '\x2', '\x2', 'i', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', 'j', 'l', '\a', '\x13', '\x2', '\x2', 'k', 'j', '\x3', '\x2', '\x2', 
		'\x2', 'k', 'l', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\x3', '\x2', '\x2', 
		'\x2', 'm', 'q', '\x5', '\x1E', '\x10', '\x2', 'n', 'o', '\x5', ' ', '\x11', 
		'\x2', 'o', 'p', '\x5', '\x1C', '\xF', '\x2', 'p', 'r', '\x3', '\x2', 
		'\x2', '\x2', 'q', 'n', '\x3', '\x2', '\x2', '\x2', 'q', 'r', '\x3', '\x2', 
		'\x2', '\x2', 'r', 'x', '\x3', '\x2', '\x2', '\x2', 's', 't', '\a', '&', 
		'\x2', '\x2', 't', 'u', '\x5', '\x1C', '\xF', '\x2', 'u', 'v', '\a', '\'', 
		'\x2', '\x2', 'v', 'x', '\x3', '\x2', '\x2', '\x2', 'w', 'k', '\x3', '\x2', 
		'\x2', '\x2', 'w', 's', '\x3', '\x2', '\x2', '\x2', 'x', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', 'y', '\x82', '\x5', '\"', '\x12', '\x2', 'z', '\x82', 
		'\x5', '&', '\x14', '\x2', '{', '\x82', '\x5', '\x16', '\f', '\x2', '|', 
		'\x82', '\x5', '\xE', '\b', '\x2', '}', '\x82', '\x5', '\x14', '\v', '\x2', 
		'~', '\x82', '\x5', '\x12', '\n', '\x2', '\x7F', '\x82', '\x5', '\x18', 
		'\r', '\x2', '\x80', '\x82', '\x5', '\x1A', '\xE', '\x2', '\x81', 'y', 
		'\x3', '\x2', '\x2', '\x2', '\x81', 'z', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'{', '\x3', '\x2', '\x2', '\x2', '\x81', '|', '\x3', '\x2', '\x2', '\x2', 
		'\x81', '}', '\x3', '\x2', '\x2', '\x2', '\x81', '~', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x7F', '\x3', '\x2', '\x2', '\x2', '\x81', '\x80', '\x3', 
		'\x2', '\x2', '\x2', '\x82', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x83', 
		'\x84', '\t', '\x4', '\x2', '\x2', '\x84', '!', '\x3', '\x2', '\x2', '\x2', 
		'\x85', '\x86', '\a', '\x3', '\x2', '\x2', '\x86', '\x87', '\a', '/', 
		'\x2', '\x2', '\x87', '\x89', '\a', '&', '\x2', '\x2', '\x88', '\x8A', 
		'\x5', '$', '\x13', '\x2', '\x89', '\x88', '\x3', '\x2', '\x2', '\x2', 
		'\x89', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '\x8B', '\x8C', '\a', '\'', '\x2', '\x2', '\x8C', '#', '\x3', 
		'\x2', '\x2', '\x2', '\x8D', '\x92', '\x5', '\f', '\a', '\x2', '\x8E', 
		'\x8F', '\a', '%', '\x2', '\x2', '\x8F', '\x91', '\x5', '\f', '\a', '\x2', 
		'\x90', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x91', '\x94', '\x3', '\x2', 
		'\x2', '\x2', '\x92', '\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x93', 
		'\x3', '\x2', '\x2', '\x2', '\x93', '%', '\x3', '\x2', '\x2', '\x2', '\x94', 
		'\x92', '\x3', '\x2', '\x2', '\x2', '\x95', '\x96', '\a', '\x3', '\x2', 
		'\x2', '\x96', '\x97', '\a', '\n', '\x2', '\x2', '\x97', '\x99', '\x5', 
		',', '\x17', '\x2', '\x98', '\x9A', '\x5', '(', '\x15', '\x2', '\x99', 
		'\x98', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\x3', '\x2', '\x2', 
		'\x2', '\x9B', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9C', '\x3', 
		'\x2', '\x2', '\x2', '\x9C', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x9D', 
		'\x9F', '\x5', '*', '\x16', '\x2', '\x9E', '\x9D', '\x3', '\x2', '\x2', 
		'\x2', '\x9E', '\x9F', '\x3', '\x2', '\x2', '\x2', '\x9F', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\xA0', '\xA1', '\a', '\v', '\x2', '\x2', '\xA1', 
		'\xA2', '\x5', ',', '\x17', '\x2', '\xA2', '\xA3', '\a', '\x6', '\x2', 
		'\x2', '\xA3', '\xA4', '\a', '!', '\x2', '\x2', '\xA4', '\xA5', '\x5', 
		'\f', '\a', '\x2', '\xA5', '\xA7', '\a', '\"', '\x2', '\x2', '\xA6', '\xA8', 
		'\x5', '*', '\x16', '\x2', '\xA7', '\xA6', '\x3', '\x2', '\x2', '\x2', 
		'\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA8', ')', '\x3', '\x2', 
		'\x2', '\x2', '\xA9', '\xAA', '\a', '\f', '\x2', '\x2', '\xAA', '\xAB', 
		'\a', '\x6', '\x2', '\x2', '\xAB', '\xAC', '\a', '!', '\x2', '\x2', '\xAC', 
		'\xAD', '\x5', '\f', '\a', '\x2', '\xAD', '\xAE', '\a', '\"', '\x2', '\x2', 
		'\xAE', '+', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB6', '\x5', '\x16', 
		'\f', '\x2', '\xB0', '\xB6', '\x5', '\xE', '\b', '\x2', '\xB1', '\xB6', 
		'\x5', '\x14', '\v', '\x2', '\xB2', '\xB6', '\x5', '\x12', '\n', '\x2', 
		'\xB3', '\xB6', '\x5', '\x18', '\r', '\x2', '\xB4', '\xB6', '\x5', '\x1C', 
		'\xF', '\x2', '\xB5', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB0', 
		'\x3', '\x2', '\x2', '\x2', '\xB5', '\xB1', '\x3', '\x2', '\x2', '\x2', 
		'\xB5', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB3', '\x3', '\x2', 
		'\x2', '\x2', '\xB5', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB6', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x11', '\x39', '@', 'L', 'S', 'Y', 'k', 'q', 
		'w', '\x81', '\x89', '\x92', '\x9B', '\x9E', '\xA7', '\xB5',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Bb.Json.Jslt.Parser
