//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JsltLexer.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Bb.Json.Jslt.Parser {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public partial class JsltLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		CURRENT_VALUE=1, RECURSIVE_DESCENT=2, ROOT_VALUE=3, SUBSCRIPT=4, WILDCARD_SUBSCRIPT=5, 
		PIPE=6, AND=7, EQ=8, GE=9, GT=10, LE=11, LT=12, NE=13, NOT=14, OR=15, 
		NEW=16, TRUE=17, FALSE=18, NULL=19, BRACE_LEFT=20, BRACE_RIGHT=21, BRACKET_LEFT=22, 
		BRACKET_RIGHT=23, COLON=24, COMMA=25, PAREN_LEFT=26, PAREN_RIGHT=27, QUESTION=28, 
		STRING=29, NUMBER=30, INT=31, WS=32, ID=33;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"CURRENT_VALUE", "RECURSIVE_DESCENT", "ROOT_VALUE", "SUBSCRIPT", "WILDCARD_SUBSCRIPT", 
		"PIPE", "AND", "EQ", "GE", "GT", "LE", "LT", "NE", "NOT", "OR", "NEW", 
		"TRUE", "FALSE", "NULL", "BRACE_LEFT", "BRACE_RIGHT", "BRACKET_LEFT", 
		"BRACKET_RIGHT", "COLON", "COMMA", "PAREN_LEFT", "PAREN_RIGHT", "QUESTION", 
		"STRING", "ESC", "UNICODE", "HEX", "SAFECODEPOINT", "NUMBER", "INT", "EXP", 
		"WS", "ID"
	};


	public JsltLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public JsltLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'@'", "'..'", "'$'", "'.'", "'*'", "'|'", "'and'", "'='", "'>='", 
		"'>'", "'<='", "'<'", "'!='", "'not'", "'or'", "'new'", "'true'", "'false'", 
		"'null'", "'{'", "'}'", "'['", "']'", "':'", "','", "'('", "')'", "'?'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "CURRENT_VALUE", "RECURSIVE_DESCENT", "ROOT_VALUE", "SUBSCRIPT", 
		"WILDCARD_SUBSCRIPT", "PIPE", "AND", "EQ", "GE", "GT", "LE", "LT", "NE", 
		"NOT", "OR", "NEW", "TRUE", "FALSE", "NULL", "BRACE_LEFT", "BRACE_RIGHT", 
		"BRACKET_LEFT", "BRACKET_RIGHT", "COLON", "COMMA", "PAREN_LEFT", "PAREN_RIGHT", 
		"QUESTION", "STRING", "NUMBER", "INT", "WS", "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "JsltLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static JsltLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '#', '\xE2', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x4', '\x1F', '\t', '\x1F', '\x4', 
		' ', '\t', ' ', '\x4', '!', '\t', '!', '\x4', '\"', '\t', '\"', '\x4', 
		'#', '\t', '#', '\x4', '$', '\t', '$', '\x4', '%', '\t', '%', '\x4', '&', 
		'\t', '&', '\x4', '\'', '\t', '\'', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\a', '\x3', '\a', 
		'\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', 
		'\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\v', '\x3', '\v', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\x3', '\r', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x3', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', 
		'\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', '\x1E', '\x3', 
		'\x1E', '\a', '\x1E', '\xA0', '\n', '\x1E', '\f', '\x1E', '\xE', '\x1E', 
		'\xA3', '\v', '\x1E', '\x3', '\x1E', '\x3', '\x1E', '\x3', '\x1F', '\x3', 
		'\x1F', '\x3', '\x1F', '\x5', '\x1F', '\xAA', '\n', '\x1F', '\x3', ' ', 
		'\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', ' ', '\x3', '!', 
		'\x3', '!', '\x3', '\"', '\x3', '\"', '\x3', '#', '\x5', '#', '\xB7', 
		'\n', '#', '\x3', '#', '\x3', '#', '\x3', '#', '\x6', '#', '\xBC', '\n', 
		'#', '\r', '#', '\xE', '#', '\xBD', '\x5', '#', '\xC0', '\n', '#', '\x3', 
		'#', '\x5', '#', '\xC3', '\n', '#', '\x3', '$', '\x3', '$', '\x3', '$', 
		'\a', '$', '\xC8', '\n', '$', '\f', '$', '\xE', '$', '\xCB', '\v', '$', 
		'\x5', '$', '\xCD', '\n', '$', '\x3', '%', '\x3', '%', '\x5', '%', '\xD1', 
		'\n', '%', '\x3', '%', '\x3', '%', '\x3', '&', '\x6', '&', '\xD6', '\n', 
		'&', '\r', '&', '\xE', '&', '\xD7', '\x3', '&', '\x3', '&', '\x3', '\'', 
		'\x3', '\'', '\a', '\'', '\xDE', '\n', '\'', '\f', '\'', '\xE', '\'', 
		'\xE1', '\v', '\'', '\x2', '\x2', '(', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\v', '\x15', '\f', '\x17', '\r', '\x19', '\xE', '\x1B', '\xF', 
		'\x1D', '\x10', '\x1F', '\x11', '!', '\x12', '#', '\x13', '%', '\x14', 
		'\'', '\x15', ')', '\x16', '+', '\x17', '-', '\x18', '/', '\x19', '\x31', 
		'\x1A', '\x33', '\x1B', '\x35', '\x1C', '\x37', '\x1D', '\x39', '\x1E', 
		';', '\x1F', '=', '\x2', '?', '\x2', '\x41', '\x2', '\x43', '\x2', '\x45', 
		' ', 'G', '!', 'I', '\x2', 'K', '\"', 'M', '#', '\x3', '\x2', '\f', '\n', 
		'\x2', '$', '$', '\x31', '\x31', '^', '^', '\x64', '\x64', 'h', 'h', 'p', 
		'p', 't', 't', 'v', 'v', '\x5', '\x2', '\x32', ';', '\x43', 'H', '\x63', 
		'h', '\x5', '\x2', '\x2', '!', '$', '$', '^', '^', '\x3', '\x2', '\x32', 
		';', '\x3', '\x2', '\x33', ';', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x4', 
		'\x2', '-', '-', '/', '/', '\x5', '\x2', '\v', '\f', '\xF', '\xF', '\"', 
		'\"', '\x5', '\x2', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x6', 
		'\x2', '\x32', ';', '\x43', '\\', '\x61', '\x61', '\x63', '|', '\x2', 
		'\xE8', '\x2', '\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\r', '\x3', '\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x13', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x15', '\x3', '\x2', '\x2', '\x2', '\x2', '\x17', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x1B', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1D', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', '\x2', '\x2', '!', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', '\x2', '\x2', '\x2', '%', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', '\x2', '\x2', '\x2', '\x2', 
		')', '\x3', '\x2', '\x2', '\x2', '\x2', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '-', '\x3', '\x2', '\x2', '\x2', '\x2', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', '\x2', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x35', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x37', '\x3', '\x2', '\x2', '\x2', '\x2', '\x39', '\x3', '\x2', '\x2', 
		'\x2', '\x2', ';', '\x3', '\x2', '\x2', '\x2', '\x2', '\x45', '\x3', '\x2', 
		'\x2', '\x2', '\x2', 'G', '\x3', '\x2', '\x2', '\x2', '\x2', 'K', '\x3', 
		'\x2', '\x2', '\x2', '\x2', 'M', '\x3', '\x2', '\x2', '\x2', '\x3', 'O', 
		'\x3', '\x2', '\x2', '\x2', '\x5', 'Q', '\x3', '\x2', '\x2', '\x2', '\a', 
		'T', '\x3', '\x2', '\x2', '\x2', '\t', 'V', '\x3', '\x2', '\x2', '\x2', 
		'\v', 'X', '\x3', '\x2', '\x2', '\x2', '\r', 'Z', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '\\', '\x3', '\x2', '\x2', '\x2', '\x11', '`', '\x3', '\x2', 
		'\x2', '\x2', '\x13', '\x62', '\x3', '\x2', '\x2', '\x2', '\x15', '\x65', 
		'\x3', '\x2', '\x2', '\x2', '\x17', 'g', '\x3', '\x2', '\x2', '\x2', '\x19', 
		'j', '\x3', '\x2', '\x2', '\x2', '\x1B', 'l', '\x3', '\x2', '\x2', '\x2', 
		'\x1D', 'o', '\x3', '\x2', '\x2', '\x2', '\x1F', 's', '\x3', '\x2', '\x2', 
		'\x2', '!', 'v', '\x3', '\x2', '\x2', '\x2', '#', 'z', '\x3', '\x2', '\x2', 
		'\x2', '%', '\x7F', '\x3', '\x2', '\x2', '\x2', '\'', '\x85', '\x3', '\x2', 
		'\x2', '\x2', ')', '\x8A', '\x3', '\x2', '\x2', '\x2', '+', '\x8C', '\x3', 
		'\x2', '\x2', '\x2', '-', '\x8E', '\x3', '\x2', '\x2', '\x2', '/', '\x90', 
		'\x3', '\x2', '\x2', '\x2', '\x31', '\x92', '\x3', '\x2', '\x2', '\x2', 
		'\x33', '\x94', '\x3', '\x2', '\x2', '\x2', '\x35', '\x96', '\x3', '\x2', 
		'\x2', '\x2', '\x37', '\x98', '\x3', '\x2', '\x2', '\x2', '\x39', '\x9A', 
		'\x3', '\x2', '\x2', '\x2', ';', '\x9C', '\x3', '\x2', '\x2', '\x2', '=', 
		'\xA6', '\x3', '\x2', '\x2', '\x2', '?', '\xAB', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\xB1', '\x3', '\x2', '\x2', '\x2', '\x43', '\xB3', '\x3', 
		'\x2', '\x2', '\x2', '\x45', '\xB6', '\x3', '\x2', '\x2', '\x2', 'G', 
		'\xCC', '\x3', '\x2', '\x2', '\x2', 'I', '\xCE', '\x3', '\x2', '\x2', 
		'\x2', 'K', '\xD5', '\x3', '\x2', '\x2', '\x2', 'M', '\xDB', '\x3', '\x2', 
		'\x2', '\x2', 'O', 'P', '\a', '\x42', '\x2', '\x2', 'P', '\x4', '\x3', 
		'\x2', '\x2', '\x2', 'Q', 'R', '\a', '\x30', '\x2', '\x2', 'R', 'S', '\a', 
		'\x30', '\x2', '\x2', 'S', '\x6', '\x3', '\x2', '\x2', '\x2', 'T', 'U', 
		'\a', '&', '\x2', '\x2', 'U', '\b', '\x3', '\x2', '\x2', '\x2', 'V', 'W', 
		'\a', '\x30', '\x2', '\x2', 'W', '\n', '\x3', '\x2', '\x2', '\x2', 'X', 
		'Y', '\a', ',', '\x2', '\x2', 'Y', '\f', '\x3', '\x2', '\x2', '\x2', 'Z', 
		'[', '\a', '~', '\x2', '\x2', '[', '\xE', '\x3', '\x2', '\x2', '\x2', 
		'\\', ']', '\a', '\x63', '\x2', '\x2', ']', '^', '\a', 'p', '\x2', '\x2', 
		'^', '_', '\a', '\x66', '\x2', '\x2', '_', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '`', '\x61', '\a', '?', '\x2', '\x2', '\x61', '\x12', '\x3', '\x2', 
		'\x2', '\x2', '\x62', '\x63', '\a', '@', '\x2', '\x2', '\x63', '\x64', 
		'\a', '?', '\x2', '\x2', '\x64', '\x14', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x66', '\a', '@', '\x2', '\x2', '\x66', '\x16', '\x3', '\x2', '\x2', 
		'\x2', 'g', 'h', '\a', '>', '\x2', '\x2', 'h', 'i', '\a', '?', '\x2', 
		'\x2', 'i', '\x18', '\x3', '\x2', '\x2', '\x2', 'j', 'k', '\a', '>', '\x2', 
		'\x2', 'k', '\x1A', '\x3', '\x2', '\x2', '\x2', 'l', 'm', '\a', '#', '\x2', 
		'\x2', 'm', 'n', '\a', '?', '\x2', '\x2', 'n', '\x1C', '\x3', '\x2', '\x2', 
		'\x2', 'o', 'p', '\a', 'p', '\x2', '\x2', 'p', 'q', '\a', 'q', '\x2', 
		'\x2', 'q', 'r', '\a', 'v', '\x2', '\x2', 'r', '\x1E', '\x3', '\x2', '\x2', 
		'\x2', 's', 't', '\a', 'q', '\x2', '\x2', 't', 'u', '\a', 't', '\x2', 
		'\x2', 'u', ' ', '\x3', '\x2', '\x2', '\x2', 'v', 'w', '\a', 'p', '\x2', 
		'\x2', 'w', 'x', '\a', 'g', '\x2', '\x2', 'x', 'y', '\a', 'y', '\x2', 
		'\x2', 'y', '\"', '\x3', '\x2', '\x2', '\x2', 'z', '{', '\a', 'v', '\x2', 
		'\x2', '{', '|', '\a', 't', '\x2', '\x2', '|', '}', '\a', 'w', '\x2', 
		'\x2', '}', '~', '\a', 'g', '\x2', '\x2', '~', '$', '\x3', '\x2', '\x2', 
		'\x2', '\x7F', '\x80', '\a', 'h', '\x2', '\x2', '\x80', '\x81', '\a', 
		'\x63', '\x2', '\x2', '\x81', '\x82', '\a', 'n', '\x2', '\x2', '\x82', 
		'\x83', '\a', 'u', '\x2', '\x2', '\x83', '\x84', '\a', 'g', '\x2', '\x2', 
		'\x84', '&', '\x3', '\x2', '\x2', '\x2', '\x85', '\x86', '\a', 'p', '\x2', 
		'\x2', '\x86', '\x87', '\a', 'w', '\x2', '\x2', '\x87', '\x88', '\a', 
		'n', '\x2', '\x2', '\x88', '\x89', '\a', 'n', '\x2', '\x2', '\x89', '(', 
		'\x3', '\x2', '\x2', '\x2', '\x8A', '\x8B', '\a', '}', '\x2', '\x2', '\x8B', 
		'*', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\a', '\x7F', '\x2', 
		'\x2', '\x8D', ',', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x8F', '\a', 
		']', '\x2', '\x2', '\x8F', '.', '\x3', '\x2', '\x2', '\x2', '\x90', '\x91', 
		'\a', '_', '\x2', '\x2', '\x91', '\x30', '\x3', '\x2', '\x2', '\x2', '\x92', 
		'\x93', '\a', '<', '\x2', '\x2', '\x93', '\x32', '\x3', '\x2', '\x2', 
		'\x2', '\x94', '\x95', '\a', '.', '\x2', '\x2', '\x95', '\x34', '\x3', 
		'\x2', '\x2', '\x2', '\x96', '\x97', '\a', '*', '\x2', '\x2', '\x97', 
		'\x36', '\x3', '\x2', '\x2', '\x2', '\x98', '\x99', '\a', '+', '\x2', 
		'\x2', '\x99', '\x38', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9B', '\a', 
		'\x41', '\x2', '\x2', '\x9B', ':', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\xA1', '\a', '$', '\x2', '\x2', '\x9D', '\xA0', '\x5', '=', '\x1F', '\x2', 
		'\x9E', '\xA0', '\x5', '\x43', '\"', '\x2', '\x9F', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '\x9F', '\x9E', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', 
		'\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA4', '\x3', '\x2', 
		'\x2', '\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', 
		'\a', '$', '\x2', '\x2', '\xA5', '<', '\x3', '\x2', '\x2', '\x2', '\xA6', 
		'\xA9', '\a', '^', '\x2', '\x2', '\xA7', '\xAA', '\t', '\x2', '\x2', '\x2', 
		'\xA8', '\xAA', '\x5', '?', ' ', '\x2', '\xA9', '\xA7', '\x3', '\x2', 
		'\x2', '\x2', '\xA9', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAA', '>', 
		'\x3', '\x2', '\x2', '\x2', '\xAB', '\xAC', '\a', 'w', '\x2', '\x2', '\xAC', 
		'\xAD', '\x5', '\x41', '!', '\x2', '\xAD', '\xAE', '\x5', '\x41', '!', 
		'\x2', '\xAE', '\xAF', '\x5', '\x41', '!', '\x2', '\xAF', '\xB0', '\x5', 
		'\x41', '!', '\x2', '\xB0', '@', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB2', 
		'\t', '\x3', '\x2', '\x2', '\xB2', '\x42', '\x3', '\x2', '\x2', '\x2', 
		'\xB3', '\xB4', '\n', '\x4', '\x2', '\x2', '\xB4', '\x44', '\x3', '\x2', 
		'\x2', '\x2', '\xB5', '\xB7', '\a', '/', '\x2', '\x2', '\xB6', '\xB5', 
		'\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', '\x2', '\x2', '\x2', 
		'\xB7', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xB8', '\xBF', '\x5', 'G', 
		'$', '\x2', '\xB9', '\xBB', '\a', '\x30', '\x2', '\x2', '\xBA', '\xBC', 
		'\t', '\x5', '\x2', '\x2', '\xBB', '\xBA', '\x3', '\x2', '\x2', '\x2', 
		'\xBC', '\xBD', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xBB', '\x3', '\x2', 
		'\x2', '\x2', '\xBD', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xC0', 
		'\x3', '\x2', '\x2', '\x2', '\xBF', '\xB9', '\x3', '\x2', '\x2', '\x2', 
		'\xBF', '\xC0', '\x3', '\x2', '\x2', '\x2', '\xC0', '\xC2', '\x3', '\x2', 
		'\x2', '\x2', '\xC1', '\xC3', '\x5', 'I', '%', '\x2', '\xC2', '\xC1', 
		'\x3', '\x2', '\x2', '\x2', '\xC2', '\xC3', '\x3', '\x2', '\x2', '\x2', 
		'\xC3', '\x46', '\x3', '\x2', '\x2', '\x2', '\xC4', '\xCD', '\a', '\x32', 
		'\x2', '\x2', '\xC5', '\xC9', '\t', '\x6', '\x2', '\x2', '\xC6', '\xC8', 
		'\t', '\x5', '\x2', '\x2', '\xC7', '\xC6', '\x3', '\x2', '\x2', '\x2', 
		'\xC8', '\xCB', '\x3', '\x2', '\x2', '\x2', '\xC9', '\xC7', '\x3', '\x2', 
		'\x2', '\x2', '\xC9', '\xCA', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCD', 
		'\x3', '\x2', '\x2', '\x2', '\xCB', '\xC9', '\x3', '\x2', '\x2', '\x2', 
		'\xCC', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xCC', '\xC5', '\x3', '\x2', 
		'\x2', '\x2', '\xCD', 'H', '\x3', '\x2', '\x2', '\x2', '\xCE', '\xD0', 
		'\t', '\a', '\x2', '\x2', '\xCF', '\xD1', '\t', '\b', '\x2', '\x2', '\xD0', 
		'\xCF', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD1', '\x3', '\x2', '\x2', 
		'\x2', '\xD1', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD3', '\x5', 
		'G', '$', '\x2', '\xD3', 'J', '\x3', '\x2', '\x2', '\x2', '\xD4', '\xD6', 
		'\t', '\t', '\x2', '\x2', '\xD5', '\xD4', '\x3', '\x2', '\x2', '\x2', 
		'\xD6', '\xD7', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD5', '\x3', '\x2', 
		'\x2', '\x2', '\xD7', '\xD8', '\x3', '\x2', '\x2', '\x2', '\xD8', '\xD9', 
		'\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\b', '&', '\x2', '\x2', '\xDA', 
		'L', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xDF', '\t', '\n', '\x2', '\x2', 
		'\xDC', '\xDE', '\t', '\v', '\x2', '\x2', '\xDD', '\xDC', '\x3', '\x2', 
		'\x2', '\x2', '\xDE', '\xE1', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xDD', 
		'\x3', '\x2', '\x2', '\x2', '\xDF', '\xE0', '\x3', '\x2', '\x2', '\x2', 
		'\xE0', 'N', '\x3', '\x2', '\x2', '\x2', '\xE1', '\xDF', '\x3', '\x2', 
		'\x2', '\x2', '\xF', '\x2', '\x9F', '\xA1', '\xA9', '\xB6', '\xBD', '\xBF', 
		'\xC2', '\xC9', '\xCC', '\xD0', '\xD7', '\xDF', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace Bb.Json.Jslt.Parser
