//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JsltParser.g4 by ANTLR 4.7

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Bb.Json.Jslt.Parser {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="JsltParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7")]
[System.CLSCompliant(false)]
public interface IJsltParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] JsltParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJson([NotNull] JsltParser.JsonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.obj"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitObj([NotNull] JsltParser.ObjContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPair([NotNull] JsltParser.PairContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray([NotNull] JsltParser.ArrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValue([NotNull] JsltParser.JsonValueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueString([NotNull] JsltParser.JsonValueStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueCodeString"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueCodeString([NotNull] JsltParser.JsonValueCodeStringContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueNumber([NotNull] JsltParser.JsonValueNumberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueInteger"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueInteger([NotNull] JsltParser.JsonValueIntegerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueBoolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueBoolean([NotNull] JsltParser.JsonValueBooleanContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueNull"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueNull([NotNull] JsltParser.JsonValueNullContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonCtor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonCtor([NotNull] JsltParser.JsonCtorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonValueList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonValueList([NotNull] JsltParser.JsonValueListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonLt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonLt([NotNull] JsltParser.JsonLtContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonLtItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonLtItem([NotNull] JsltParser.JsonLtItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.jsonpath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJsonpath([NotNull] JsltParser.JsonpathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.subscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscript([NotNull] JsltParser.SubscriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.subscriptables"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscriptables([NotNull] JsltParser.SubscriptablesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.subscriptableBareword"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscriptableBareword([NotNull] JsltParser.SubscriptableBarewordContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.subscriptable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSubscriptable([NotNull] JsltParser.SubscriptableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.sliceable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSliceable([NotNull] JsltParser.SliceableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] JsltParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] JsltParser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.orExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpression([NotNull] JsltParser.OrExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="JsltParser.notExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpression([NotNull] JsltParser.NotExpressionContext context);
}
} // namespace Bb.Json.Jslt.Parser
