//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bb.Expressions.CsharpGenerators {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceString() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bb.git.Expressions.CsharpGenerators.ResourceString", typeof(ResourceString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The &apos;Comment&apos; property of the CodeCommentStatement &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string Argument_NullComment {
            get {
                return ResourceManager.GetString("Argument_NullComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The total arity specified in &apos;{0}&apos; does not match the number of TypeArguments supplied.  There were &apos;{1}&apos; TypeArguments supplied..
        /// </summary>
        internal static string ArityDoesntMatch {
            get {
                return ResourceManager.GetString("ArityDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à auto-generated&gt;.
        /// </summary>
        internal static string AutoGen_Comment_Line1 {
            get {
                return ResourceManager.GetString("AutoGen_Comment_Line1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This code was generated by a tool..
        /// </summary>
        internal static string AutoGen_Comment_Line2 {
            get {
                return ResourceManager.GetString("AutoGen_Comment_Line2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changes to this file may cause incorrect behavior and will be lost if.
        /// </summary>
        internal static string AutoGen_Comment_Line4 {
            get {
                return ResourceManager.GetString("AutoGen_Comment_Line4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à the code is regenerated..
        /// </summary>
        internal static string AutoGen_Comment_Line5 {
            get {
                return ResourceManager.GetString("AutoGen_Comment_Line5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no CodeDom provider defined for the language..
        /// </summary>
        internal static string CodeDomProvider_NotDefined {
            get {
                return ResourceManager.GetString("CodeDomProvider_NotDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The output writer for code generation and the writer supplied don&apos;t match and cannot be used. This is generally caused by a bad implementation of a CodeGenerator derived class..
        /// </summary>
        internal static string CodeGenOutputWriter {
            get {
                return ResourceManager.GetString("CodeGenOutputWriter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This code generation API cannot be called while the generator is being used to generate something else..
        /// </summary>
        internal static string CodeGenReentrance {
            get {
                return ResourceManager.GetString("CodeGenReentrance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The file name &apos;{0}&apos; was already in the collection..
        /// </summary>
        internal static string DuplicateFileName {
            get {
                return ResourceManager.GetString("DuplicateFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Timed out waiting for a program to execute. The command being executed was {0}..
        /// </summary>
        internal static string ExecTimeout {
            get {
                return ResourceManager.GetString("ExecTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Element type {0} is not supported..
        /// </summary>
        internal static string InvalidElementType {
            get {
                return ResourceManager.GetString("InvalidElementType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Identifier &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string InvalidIdentifier {
            get {
                return ResourceManager.GetString("InvalidIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The identifier:&quot;{0}&quot; on the property:&quot;{1}&quot; of type:&quot;{2}&quot; is not a valid language-independent identifier name. Check to see if CodeGenerator.IsValidLanguageIndependentIdentifier allows the identifier name..
        /// </summary>
        internal static string InvalidLanguageIdentifier {
            get {
                return ResourceManager.GetString("InvalidLanguageIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Argument {0} cannot be null or zero-length..
        /// </summary>
        internal static string InvalidNullEmptyArgument {
            get {
                return ResourceManager.GetString("InvalidNullEmptyArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The CodeChecksumPragma file name &apos;{0}&apos; contains invalid path characters..
        /// </summary>
        internal static string InvalidPathCharsInChecksum {
            get {
                return ResourceManager.GetString("InvalidPathCharsInChecksum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid Primitive Type: {0}. Consider using CodeObjectCreateExpression..
        /// </summary>
        internal static string InvalidPrimitiveType {
            get {
                return ResourceManager.GetString("InvalidPrimitiveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The region directive &apos;{0}&apos; contains invalid characters.  RegionText cannot contain any new line characters..
        /// </summary>
        internal static string InvalidRegion {
            get {
                return ResourceManager.GetString("InvalidRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The type name:&quot;{0}&quot; on the property:&quot;{1}&quot; of type:&quot;{2}&quot; is not a valid language-independent type name..
        /// </summary>
        internal static string InvalidTypeName {
            get {
                return ResourceManager.GetString("InvalidTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This CodeDomProvider does not support this method..
        /// </summary>
        internal static string NotSupported_CodeDomAPI {
            get {
                return ResourceManager.GetString("NotSupported_CodeDomAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This CodeDomProvider type does not have a constructor that takes providerOptions - &quot;{0}&quot;..
        /// </summary>
        internal static string Provider_does_not_support_options {
            get {
                return ResourceManager.GetString("Provider_does_not_support_options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {unknown}.
        /// </summary>
        internal static string toStringUnknown {
            get {
                return ResourceManager.GetString("toStringUnknown", resourceCulture);
            }
        }
    }
}
